version: '3.8'

services:
  kibou:
    image: kibou-registery
    build: .
    ports:
      - "8000-8999:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: 12344567
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: kibou_db
      POSTGRES_PASSWORD: 12344567
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: