spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-ctue7abqf0us73f384ag-a.oregon-postgres.render.com:5432/kibou_db}
    username: ${SPRING_DATASOURCE_USERNAME:kibou_db_user}
    password: ${SPRING_DATASOURCE_PASSWORD:AsvvNkaxwoNpis9C6OXzqQv9BgbQcRAO}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:9000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
