spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/kibou_db}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:olusolaalao}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:1234}}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:9000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
