spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379



  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


server:
  port: ${PORT:9000}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
