# Database URL
spring.datasource.url=jdbc:postgresql://dpg-ctpe91popnds73fotivg-a.oregon-postgres.render.com:5432/kibou_database_svie
spring.datasource.username=kibou_database_svie_user
spring.datasource.password=kqrKEkOYp6jRn4xTIt0bWbedm3wdL2iw
#spring.datasource.url=jdbc:postgresql://localhost:5433/kibou_db
#spring.datasource.username=postgres
#spring.datasource.password=Olawumi
spring.datasource.driver-class-name=org.postgresql.Driver




# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging and Debug
logging.level.org.springframework=INFO
logging.level.org.hibernate=INFO
server.port=8181
server.error.whitelabel.enabled=false
debug=true

#logging.level.org.springframework.jdbc.core=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE

spring.task.scheduling.enabled=true

