version: '3.8'

services:
  kibou:
    image: kibou-registery
    build: .
    ports:
      - "9000:9000"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
      POSTGRES_USER: ${POSTGRES_USER:-default_user}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: kibou_db
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
