name: Branch Naming Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name from PR
        id: pr_branch
        uses: actions/github-script@v5
        with:
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            return pr.data.head.ref;
          result-encoding: string

      - name: Check If Admin
        id: check_admin
        uses: actions/github-script@v5
        with:
          script: |
            const current_user = (process.env.GITHUB_ACTOR).toLowerCase();
            const admins = ["realwale", "olusolaa", "toluwase1"];  // Add the list of admin usernames here
            const is_admin = admins.includes(current_user);
            console.log(`Current user: ${current_user}`);
            console.log(`Is admin: ${is_admin}`);
            return is_admin.toString();
          result-encoding: string

      - name: Check Branch Name Prefix
        id: check_prefix
        if: ${{ steps.check_admin.outputs.result != 'true' }}
        run: |
          branch_name="${{ steps.pr_branch.outputs.result }}"
          expected_prefix="$(echo $GITHUB_ACTOR | tr '[:upper:]' '[:lower:]')/"
          if [[ ! $branch_name =~ ^$expected_prefix ]]; then
            echo "Branch name: $branch_name"
            echo "Expected prefix: $expected_prefix"
            echo "Branch name does not follow the expected naming convention."
            exit 1
          fi
        shell: bash

      - name: Check Issue Match
        if: ${{ steps.check_prefix.outcome != 'failure' }}
        uses: actions/github-script@v5
        with:
          script: |
            const branch_name = "${{ steps.pr_branch.outputs.result }}";
            const issue_number_regex = /\/(\d+)-/;
            const match = branch_name.match(issue_number_regex);
            let issue_number;
            let issue_exists = false;
            
            if (match) {
              issue_number = match[1];
            }
            
            try {
              const issue = await github.rest.issues.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue_number,
              });
              
              if (issue.data && issue.data.title) {
                const expected_branch_suffix = `${issue_number}-${issue.data.title.replace(/\s+/g, '-').toLowerCase()}`;
                if (branch_name.toLowerCase().includes(expected_branch_suffix)) {
                  issue_exists = true;
                }
              }
            } catch (error) {
              if (error.status === 404) {
                console.log("Your branch does not target any open issue.");
                core.setFailed("Issue not found.");
              } else {
                console.log(`Error fetching issue: ${error}`);
              }
            }
            
            if (!issue_exists && issue_number) {
              console.log(`Branch name: ${branch_name}`);
              console.log(`Expected branch suffix based on issue title: ${issue_number}-[issue-title]`);
              console.log("Your branch does not match the title of the targeted issue.");
              core.setFailed("Issue match check failed.");
            }
          result-encoding: string
